# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master
  - development

pool:
  vmImage: "windows-2022"

variables:
  buildConfiguration: "Release"

steps:
  - task: DotNetCoreCLI@2
    displayName: Build solution
    inputs:
      command: "build"
      arguments: "--configuration $(buildConfiguration)"

  - task: DotNetCoreCLI@2
    displayName: "Run tests"
    inputs:
      command: "test"
      projects: '**/*Tests/*.csproj'
      arguments: "--no-build --configuration $(buildConfiguration) --collect "Code coverage""

  - task: DotNetCoreCLI@2
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: "Publish Artifacts"
    inputs:
      command: "publish"
      publishWebProjects: true
      arguments: "--configuration $(buildConfiguration) --no-restore --output $(Build.ArtifactStagingDirectory)"
      zipAfterPublish: true
  
  - publish: $(Build.ArtifactStagingDirectory)
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    artifact: drop
    patterns: "**/*.zip"
    displayName: "Upload Artifacts"